- name: Ensure productivity packages are the latest.
  become: yes
  homebrew_cask: name={{ item }} state=latest
  with_items:
    - alfred
    - Keepassxc
    - keka
    - appcleaner
    - trello-x
    - flux
    - spark
    - spectacle
    - boostnote
    - qlcolorcode
    - qlstephen
    - qlmarkdown
    - quicklook-json
    - qlimagesize
    - provisionql