- name: Ensure cask-productivity packages are the latest.
  become: no
  homebrew_cask: name={{ item }} state=latest
  with_items:
    - alfred
    - Keepassxc
    - todoist
    - keka
    - appcleaner
    - trello-x
    - f-lux
    - boostnote
    - libreoffice