- name: Ensure homebrew-editors are the latest.
  become: no
  homebrew: name={{ item }} state=latest
  with_items:
    - vim
    - neovim

- name: Ensure cask-editors are the latest.
  become: no
  homebrew_cask: name={{ item }} state=latest
  with_items:
    - pycharm-ce
    - visual-studio-code
    - intellij-idea-ce