- name: Ensure database packages are the latest.
  become: no
  homebrew: name={{ item }} state=latest
  with_items:
    - mysql
    - mongodb 
    - sqlite

- name: Ensure database gui packages are the latest.
  become: no
  homebrew_cask: name={{ item }} state=latest
  with_items:
    - mysqlworkbench
    - robo-3t