- name: Ensure homebrew-devtool packages are the latest.
  become: no
  homebrew: name={{ item }} state=latest
  with_items:
    - zsh
    - tree
    - tmux
    - wget
    - git
    - node

- name: Ensure cask-devtool packages are the latest.
  become: no
  homebrew_cask: name={{ item }} state=latest
  with_items:
    - iterm2
    - dash
    - ranger
    - filezilla
    - sourcetree