- name: Ensure devtool packages are the latest.
  become: no
  homebrew: name={{ item }} state=latest
  with_items:
    - tree
    - tmux
    - wget
    - git
    - node
    - pipenv

- name: Ensure devtool packages are the latest.
  become: no
  homebrew_cask: name={{ item }} state=latest
  with_items:
    - iterm2
    - dash
    - ranger
    - sourcetree